package project.euler.problems.problem20;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collections;
import project.euler.Problem;

/**
 * How many distinct terms are in the sequence generated by a<sup>b</sup> for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 * 
 * @author LZOU
 */
public class Problem29 extends Problem {
    private final int A_LO = 2;
    private final int A_HI = 100;
    private final int B_LO = 2;
    private final int B_HI = 100;
    
    public Problem29() {
        super(29);
        
        ArrayList<BigInteger> combinations = new ArrayList<BigInteger>();
        for (int a = A_LO; a <= A_HI; a++) {
            for (int b = B_LO; b <= B_HI; b++) {
                BigInteger number = power(a, b);
                if (!combinations.contains(number))
                    combinations.add(number);
            }
        }
        Collections.sort(combinations);
        setAnswer(combinations.size());
    }
    
    private BigInteger power(int a, int b) {
        BigInteger number = BigInteger.ONE;
        for (int i = 0; i < b; i++)
            number = number.multiply(BigInteger.valueOf(a));
        return number;
    }
}
